language: go
go:
- "1.13.x"

env:
  global:
  - GO111MODULE=on

dist: bionic
addons:
  apt:
    packages:
    - ninja-build
    - gperf

install:
- gem install ronn

script:
- RUNTESTS=1 ./compile.sh
